# Generated by Django 3.2.7 on 2021-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.PositiveSmallIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'января'), (2, 'февраля'), (3, 'марта'), (4, 'апреля'), (5, 'мая'), (6, 'июня'), (7, 'июля'), (8, 'августа'), (9, 'сентября'), (10, 'октября'), (11, 'ноября'), (12, 'декабря')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.PositiveSmallIntegerField(max_length=4),
        ),
    ]
