# Generated by Django 3.2.7 on 2021-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210905_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
