# Generated by Django 3.2.7 on 2021-09-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210911_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='files',
            field=models.ManyToManyField(to='events.Images'),
        ),
    ]
