# Generated by Django 3.2.7 on 2021-09-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='files',
        ),
        migrations.AddField(
            model_name='event',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.image'),
        ),
    ]
