# Generated by Django 3.2.7 on 2021-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210915_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='files',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
