# Generated by Django 4.1.7 on 2023-04-30 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_textpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpage',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
