# Generated by Django 4.1.7 on 2023-08-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_textpage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['year', 'month', 'day']},
        ),
        migrations.AddField(
            model_name='textpage',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
