# Generated by Django 4.1.7 on 2023-08-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_options_textpage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textpage',
            name='page',
        ),
    ]
