# Generated by Django 4.1.7 on 2023-08-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_textpage_options_alter_event_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
