# Generated by Django 4.1.7 on 2023-08-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_textpage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpage',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
